// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AzureTackleAnalyzer.Tests")>]
[<assembly: AssemblyProductAttribute("AzureTackleAnalyzer")>]
[<assembly: AssemblyVersionAttribute("3.22.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-12-08T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("3.22.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.22.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","ad927a4fc51c240225e8bec9af7799527f392652")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AzureTackleAnalyzer.Tests"
    let [<Literal>] AssemblyProduct = "AzureTackleAnalyzer"
    let [<Literal>] AssemblyVersion = "3.22.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-12-08T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "3.22.0"
    let [<Literal>] AssemblyInformationalVersion = "3.22.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "ad927a4fc51c240225e8bec9af7799527f392652"
