// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AzureTackleAnalyzer")>]
[<assembly: AssemblyProductAttribute("AzureTackleAnalyzer")>]
[<assembly: AssemblyVersionAttribute("0.3.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-12-22T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.3.3")>]
[<assembly: AssemblyInformationalVersionAttribute("0.3.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","8ffa1d42d6a070ca4ebc8a97cdf45ace34393adc")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AzureTackleAnalyzer"
    let [<Literal>] AssemblyProduct = "AzureTackleAnalyzer"
    let [<Literal>] AssemblyVersion = "0.3.3"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-12-22T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.3.3"
    let [<Literal>] AssemblyInformationalVersion = "0.3.3"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "8ffa1d42d6a070ca4ebc8a97cdf45ace34393adc"
