// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Examples")>]
[<assembly: AssemblyProductAttribute("AzureTackleAnalyzer")>]
[<assembly: AssemblyVersionAttribute("0.3.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-12-16T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.3.2")>]
[<assembly: AssemblyInformationalVersionAttribute("0.3.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","ba713bee009ec63e1ecbc841fb2c68bbfffdeb0b")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Examples"
    let [<Literal>] AssemblyProduct = "AzureTackleAnalyzer"
    let [<Literal>] AssemblyVersion = "0.3.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-12-16T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.3.2"
    let [<Literal>] AssemblyInformationalVersion = "0.3.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "ba713bee009ec63e1ecbc841fb2c68bbfffdeb0b"
