name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run: dotnet fake build
    # - name: Test
    #   run: dotnet fake build -t test
    - name: Build
      if: runner.os == 'Windows'
      run: ./build.cmd
